# conf1.toml

# rtsp_user = ""        # uncomment and fill this to override RTSP_USER env var
# rtsp_pass = ""        # uncomment and fill this to override RTSP_PASS env var
rtsp_host = "192.168.1.8"
rtsp_port = 554

vlc_path = 'C:\Program Files (x86)\VideoLAN\VLC\vlc.exe'
minimal_view = true

rtp_caching = 100
default_quality = "HIGH"
default_codec = "H264"

[channels] # optional
1 = "front"
2 = "back"

max_channel = 16 # if no channels provided we have this many numbered channels

[channel_groups]
doors = [1, 2]

initial_group_name = "doors"
